### ISSUE TITLE
Working Demo for All Data Challenges

### ISSUE THREAD

**Issue by jejjohnson** [jejjohnson/ml4ssh#3]
We want working pipelines for each of these data challenges with all batteries included.

---
**Data Challenges**

- [ ] QG Simulation (OSSE 2022b)
- [ ] NATL60 (OSSE 2020a)
- [ ] Altimetry (OSE 2021b)
- [ ] Global Altimetry (OSE 2023a)

---
**SubTasks**

- [ ] Data Download
- [ ] Data Viz
- [ ] Data Viz (Interactive)
- [ ] Data Preprocess
- [ ] AlongTrack Model Demo
- [ ] Experiment
- [ ] Inference
- [ ] Analysis
- [ ] Analysis (Interactive)
